# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FXW3mtBmtFbFXWWZHFBn656yQbxsZ98F
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_excel('databaseHR-IT-CEO.xlsx')

##### Data Quality Checks ####

#cleaning columns spaces before and after and to be lower
df.columns = df.columns.str.strip().str.lower()

#make all columns the same to be lower case
df['level'] = df['level'].str.strip().str.lower()

#make all columns the same to be lower case
df['job title'] = df['job title'].str.strip().str.lower()

#make all columns the same to be lower case
df['department'] = df['department'].str.strip().str.lower()

df['full english name'] = df['full english name'].str.strip().str.lower()

#make all columns the same to be lower case
df['unit'] = df['unit'].str.strip().str.lower()

df['sector'] = df['sector'].str.strip().str.lower()

df['department manager'] = df['department manager'].str.strip().str.lower()

df['sub unit manager'] = df['sub unit manager'].str.strip().str.lower()

df['top level'] = df['top level'].str.strip().str.lower()

df['starting date'] = pd.to_datetime(df['starting date'])

duplicates = df[df['employee id'].duplicated()]
duplicates

df[df['unit manager'].isnull()]

df[df['top level'].isnull()]

(df.isnull().sum() / len(df)) * 100

df.head()

files.download('final_hr_data.csv')