# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FXW3mtBmtFbFXWWZHFBn656yQbxsZ98F
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_excel('databaseHR-IT-CEO.xlsx')

df. head ()

##### Data Quality Checks ####

#cleaning columns spaces before and after and to be lower
df.columns = df.columns.str.strip().str.lower()

#make all columns the same to be lower case
df['level'] = df['level'].str.strip().str.lower()

#make all columns the same to be lower case
df['job title'] = df['job title'].str.strip().str.lower()

#make all columns the same to be lower case
df['department'] = df['department'].str.strip().str.lower()

df['full english name'] = df['full english name'].str.strip().str.lower()

#make all columns the same to be lower case
df['unit'] = df['unit'].str.strip().str.lower()

df['sector'] = df['sector'].str.strip().str.lower()

df['department manager'] = df['department manager'].str.strip().str.lower()

df['sub unit manager'] = df['sub unit manager'].str.strip().str.lower()

df['top level'] = df['top level'].str.strip().str.lower()

df['starting date'] = pd.to_datetime(df['starting date'])

duplicates = df[df['employee id'].duplicated()]
duplicates

###### Missing Values Analysis  ######

#Getting The sum of missingn values in columns
missing_cols = df.isnull().sum()
missing_cols = missing_cols[missing_cols > 0]

#Getting The sum of missingn values in columns and sorting them.

missing_cols.sort_values(ascending=False)

df[df['unit manager'].isnull()]

df[df['top level'].isnull()]

(df.isnull().sum() / len(df)) * 100

df.head()

# Handling Missing Values

"""**Handling Strategy**

| Column | Action Taken | Reason |
|--------|--------------|--------|
| Unit Manager | Filled with "No Manager" | Missing values are acceptable for direct reporting employees |
| Top Level  | Left as it is   |  Missing values are logically expected |
| Email | Investigated manually | Email is considered critical employee information |
"""

df = df.drop(columns=['unit manager'])

df.columns

"""Missing values in the 'top level' column were replaced with "no manager" to represent employees without top level management."""

df['top level'] = df['top level'].fillna('no manager')

df['top level']

df['email'] = df['email'].str.lower()

df['email'] = df['email'].fillna('no email')

df['email']

"""##Visualizations"""

import matplotlib.pyplot as plt

##Separate Numerical columns from Object columns.
num_cols = df.select_dtypes(include='number').columns
cat_cols = df.select_dtypes(include='object').columns

num_cols

cat_cols

df['department'].value_counts().plot(kind='bar')
plt.title("Department Count")
plt.xlabel("Department")
plt.ylabel("Count")
plt.show()

df['level'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.ylabel("")
plt.title("levels")
plt.show()

cross = pd.crosstab(df['department'], df['level'])

cross.plot(kind='bar', stacked=True)

plt.title("Department vs Level Distribution")
plt.xlabel("Department")
plt.ylabel("Count")
plt.show()

mgr_counts = df.groupby(['department', 'department manager']).size()
mgr_counts

mgr_counts.head(10).plot(kind='barh')

plt.title("Top Department Managers by Number of Employees")
plt.xlabel("Number of Employees")
plt.ylabel("Manager")
plt.show()

df.groupby(['department', 'department manager']).size()

!pip install plotly

import plotly.express as px
import plotly.graph_objects as go

fig = px.bar(
    df['department manager'].value_counts().reset_index(),
    x='department manager',
    y='count',
    title='Employees per Department'
)

fig.show()

missing = df.isnull().sum().reset_index()

missing.columns = ['column', 'missing_count']

fig = px.bar(
    missing,
    x='column',
    y='missing_count',
    title='Missing Values'
)

fig.show()

df.to_csv('final_hr_data.csv', index=False)

files.download('final_hr_data.csv')